name: neuro
channels:
  - conda-forge
  - nvidia
  - pytorch
dependencies:
  - python=3.9
  - pip
  - pytorch-cuda=11.7
  - pytorch=1.13
  - torchvision
  - torchaudio
  - ffmpeg=5
  - pip:
    - openai-whisper
    - pyyaml
    - numpy
    - setuptools-rust==1.5.2
