version: '3'

services:
  text-generator:
    image: momiji-text-generator
    environment:
      SERVER_MODEL_NAME_OR_PATH: model
      SERVER_USE_STUB: True
    ports:
      - '8080:8080'

  speech-recognition:
    image: momiji-speech-recognition
    environment:
      SERVER_MODEL_NAME_OR_PATH: model
      SERVER_USE_STUB: True
    ports:
      - '8081:8080'

  image-caption:
    image: momiji-image-caption
    environment:
      SERVER_MODEL_NAME_OR_PATH: model
      SERVER_USE_STUB: True
    ports:
      - '8082:8080'

  image-generator:
    image: momiji-image-generator
    environment:
      SERVER_MODEL_NAME_OR_PATH: model
      SERVER_USE_STUB: True
    ports:
      - '8083:8080'
