name: neuro
channels:
  - conda-forge
  - nvidia
  - pytorch
dependencies:
  - python=3.10
  - pip
  - pytorch-cuda=11.7
  - pytorch=1.13
  - torchvision
  - torchaudio
  - pip:
    - fastapi==0.92.0
    - uvicorn==0.20.0
    - pyyaml==6.0
    - cachetools==5.3.0
