name: neuro
channels:
  - conda-forge
  - nvidia
  - pytorch
dependencies:
  - pip
  - pytorch=1.13
  - torchvision
  - torchaudio
#  - pytorch-cuda=11.7
  - python=3.9
  - pip:
    - transformers==4.26.1
    - fastapi==0.92.0
    - uvicorn==0.20.0
